# Setup
title:            Neural Networks and Chill
tagline:          'Michele Tonutti'
description:      'Thoughts and adventures in data science and machine learning'

author:
  name:           'Michele Tonutti'
baseurl:          /

paginate:         5
paginate_path:    '_posts/page:num/'
# Custom vars
version:          2.1.0

github:           http://github.com/michetonu

gems:
  - jekyll-archives
  
future: true

jekyll-archives:
  enabled:
    - year
    - month
    - tag
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
