# Setup
title:            Neural Networks and Chill
tagline:          'Michele Tonutti'
description:      'Thoughts and adventures in data science and machine learning'

author:
  name:           'Michele Tonutti'
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:           http://github.com/michetonu

future: true
