# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Neural Networks and Chill
tagline:          'Michele Tonutti'
description:      'Thoughts on Data Science and Machine Learning'

author:
  name:           'Michele Tonutti'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
